"""建一张表：日报

D14。**它是快照不是视图** —— 数字在生成那一刻固定，此后不随平台回填变化，理由见
src/adpilot/models/report.py 的类 docstring（客户上周收到的日报今天再打开数字变了，
比数字不够准更伤）。两版人话都存（LLM 原文 + 人工修订后），前者永不修改。

Revision ID: 1ddd56e7bf13
Revises: dc86fa247bda
Create Date: 2026-08-21 12:02:28.098029
"""

# 🔴 autogenerate 出来的是**草稿**，提交前人看一遍：改名会被生成成 drop + add
# （数据静默丢失），部分索引的 diff 也不可信。见 docs/design/2026-08-19-schema-migration.md

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1ddd56e7bf13"
down_revision: str | Sequence[str] | None = "dc86fa247bda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("stat_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("spend", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("conversions", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("baseline_date", sa.Date(), nullable=True),
        sa.Column("baseline_spend", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("baseline_conversions", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("actions_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alerts_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_call_id", sa.BigInteger(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_reports_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["llm_call_id"],
            ["llm_calls.id"],
            name=op.f("fk_reports_llm_call_id_llm_calls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "account_id", "stat_date", name=op.f("uq_reports_account_id_stat_date")
        ),
    )
    op.create_index(
        op.f("ix_reports_account_id_status_stat_date"),
        "reports",
        ["account_id", "status", "stat_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_account_id_status_stat_date"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
