"""alerts

Revision ID: 477c9b75e27f
Revises: 695784a6f300
Create Date: 2026-08-20 17:19:54.836951
"""

# 🔴 autogenerate 出来的是**草稿**，提交前人看一遍：改名会被生成成 drop + add
# （数据静默丢失），部分索引的 diff 也不可信。见 docs/design/2026-08-19-schema-migration.md

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "477c9b75e27f"
down_revision: str | Sequence[str] | None = "695784a6f300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("message", sa.String(length=512), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_alerts_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        op.f("ix_alerts_status_opened_at"), "alerts", ["status", "opened_at"], unique=False
    )
    op.create_index(
        "uq_alerts_open_subject",
        "alerts",
        ["account_id", "kind", "subject"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_alerts_open_subject", table_name="alerts", postgresql_where=sa.text("status = 'open'")
    )
    op.drop_index(op.f("ix_alerts_status_opened_at"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
