"""余额快照表

Revision ID: 695784a6f300
Revises: 9c2cb6f879ff
Create Date: 2026-08-20 17:02:16.640319
"""

# 🔴 autogenerate 出来的是**草稿**，提交前人看一遍：改名会被生成成 drop + add
# （数据静默丢失），部分索引的 diff 也不可信。见 docs/design/2026-08-19-schema-migration.md

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "695784a6f300"
down_revision: str | Sequence[str] | None = "9c2cb6f879ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("available", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ad_accounts.id"],
            name=op.f("fk_balances_account_id_ad_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balances")),
        sa.UniqueConstraint(
            "account_id", "captured_at", name=op.f("uq_balances_account_id_captured_at")
        ),
    )
    op.create_index(
        op.f("ix_balances_account_id_captured_at"),
        "balances",
        ["account_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_balances_account_id_captured_at"), table_name="balances")
    op.drop_table("balances")
    # ### end Alembic commands ###
